<a href="https://colab.research.google.com/github/natalia973/Data-Science-Data-Analytics/blob/main/An%C3%A1lisePython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#cria uma matriz unidimensional
matriz = np.array([12,13,15,16,17])
print(matriz)
print(type(matriz))


[12 13 15 16 17]
<class 'numpy.ndarray'>


In [13]:
#Cria matriz bidimensional
k = np.array([[2,1,3],[4,5,6] , [9,20,34]])
print(k)
#mostra um elemento específico de k
print(k[0][1])
#formato da matriz k, 3 linhas e 3 colunas
print(k.shape)
#mostra o desvio padrão da matriz k
print(k.std())
#mostra a média de k
print(k.mean())


[[ 2  1  3]
 [ 4  5  6]
 [ 9 20 34]]
1
(3, 3)
10.241527663824812
9.333333333333334


In [3]:
#criar um array com um tipo específico
#atribuir o tipo do array para um float de 64 bits.
matrizF= np.array([2,3,4,5] , dtype=np.float64)
print(matrizF)
print(type(matrizF))


[2. 3. 4. 5.]
<class 'numpy.ndarray'>


In [4]:
#Converter um array float em um array inteiro
matrizFloat = np.array([2.6 , 7.8 , 9.0, 3.5], dtype = np.int8)
print(matrizFloat)




[2 7 9 3]


In [5]:
#Matrizes  - Cria uma matriz quadrada com a diagonal principal com valores 1 e os outros 0.
diagonal = np.eye(4)
print(diagonal)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
#Criação de valores aleatórios entre 0 e 1:
random = np.random.random((7))
print(random)

[0.84767192 0.70728413 0.54519941 0.07190679 0.59019661 0.84154013
 0.01098968]
